status:
  path: /
  defaults: { _controller: controller.default:indexAction }
  methods: [ GET ]

shutdown:
  path: /
  defaults: { _controller: controller.default:shutdownAction }
  methods: [ POST ]
